# Generated by Django 6.1.1 on 2026-09-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backfill_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.tenant'),
        ),
    ]
