# Generated by Django 6.1.1 on 2026-10-01 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_events(apps, schema_editor):
    Audit = apps.get_model('core', 'AuditLog')
    for event in Audit.objects.select_related('branch', 'user').iterator():
        event.tenant_id = event.branch.tenant_id if event.branch_id else None
        event.actor_name = event.user.username if event.user_id else 'System'
        event.save(update_fields=['tenant', 'actor_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditlog_branch_alter_sequence_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='kind',
            field=models.CharField(db_index=True, default='business', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='outcome',
            field=models.CharField(db_index=True, default='success', max_length=12),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='route',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(db_index=True, max_length=36)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(db_index=True, max_length=12)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(preserve_existing_events, migrations.RunPython.noop),
    ]
