# Generated by Django 6.1.1 on 2026-09-25 09:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='Part code (SKU)')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=60)),
                ('part_type', models.CharField(choices=[('oem', 'Genuine (OEM)'), ('aftermarket', 'Aftermarket')], default='aftermarket', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='new', max_length=20)),
                ('oem_number', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='OEM part number')),
                ('unit', models.CharField(default='each', help_text='each, set, pair, litre…', max_length=20)),
                ('bin_location', models.CharField(blank=True, help_text='Shelf / bin, e.g. A3-02', max_length=40)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Retail price')),
                ('trade_price', models.DecimalField(blank=True, decimal_places=2, help_text='Used for trade customers (garages, mechanics). Optional.', max_digits=12, null=True, verbose_name='Trade price')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Flag as low stock at or below this. 0 = don't track.", max_digits=12)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Usual order quantity')),
                ('is_universal', models.BooleanField(default=False, help_text='Fits any vehicle (oil, bulbs, wipers…)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=60)),
                ('kind', models.CharField(choices=[('oem', 'OEM / genuine number'), ('alt', 'Interchange (other brand)'), ('old', 'Superseded (old number)')], default='alt', max_length=10)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_refs', to='catalog.part')),
            ],
            options={
                'ordering': ['kind', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year_from', models.PositiveSmallIntegerField()),
                ('year_to', models.PositiveSmallIntegerField()),
                ('engine', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['make', 'model', 'year_from'],
                'unique_together': {('make', 'model', 'year_from', 'year_to', 'engine')},
            },
        ),
        migrations.AddField(
            model_name='part',
            name='fits',
            field=models.ManyToManyField(blank=True, related_name='parts', to='catalog.vehicle'),
        ),
    ]
