# Generated by Django 6.1.1 on 2026-09-29 19:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0002_branch_tenant_alter_sequence_name_auditlog_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('bin_location', models.CharField(blank=True, max_length=40)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='part',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='part',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.CharField(max_length=40, verbose_name='Part code (SKU)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='category_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='part_tenant_sku'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('tenant', 'barcode'), name='part_tenant_barcode'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='supplier_tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('tenant', 'make', 'model', 'year_from', 'year_to', 'engine'), name='vehicle_tenant_identity'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='core.branch'),
        ),
        migrations.AddField(
            model_name='branchstock',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_stocks', to='catalog.part'),
        ),
        migrations.AddConstraint(
            model_name='branchstock',
            constraint=models.UniqueConstraint(fields=('branch', 'part'), name='stock_branch_part'),
        ),
    ]
