# Generated by Django 6.1.1 on 2026-09-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_legacy_part_stock'),
        ('core', '0004_alter_auditlog_branch_alter_sequence_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='part',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
    ]
