# Generated by Django 6.1.1 on 2026-09-29 19:05

from decimal import Decimal
from django.db import migrations, models


def copy_cost(apps, schema_editor):
    Stock = apps.get_model("catalog", "BranchStock")
    for item in Stock.objects.select_related("part").iterator():
        item.cost_price = item.part.cost_price
        item.save(update_fields=["cost_price"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_tenant_alter_part_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstock',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.RunPython(copy_cost, migrations.RunPython.noop),
    ]
