# Generated by Django 6.1.1 on 2026-10-01 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_branchstock_cost_price'),
        ('core', '0004_alter_auditlog_branch_alter_sequence_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('create', 'Add new parts only'), ('update', 'Add and update matching SKUs')], max_length=10)),
                ('status', models.CharField(choices=[('ready', 'Ready to import'), ('imported', 'Imported'), ('cancelled', 'Cancelled')], default='ready', max_length=12)),
                ('rows', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
