# Generated by Django 6.1.1 on 2026-09-29 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_tenant_alter_sequence_name_auditlog_branch_and_more'),
        ('sales', '0002_customer_tenant_sale_branch_alter_sale_number_and_more'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='jobcard',
            constraint=models.UniqueConstraint(fields=('branch', 'number'), name='job_branch_number'),
        ),
    ]
