# Generated by Django 6.1.1 on 2026-09-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditlog_branch_alter_sequence_branch_and_more'),
        ('workshop', '0002_jobcard_branch_alter_jobcard_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch'),
        ),
    ]
