# Generated by Django 6.1.1 on 2026-09-25 09:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('open', 'Checked in'), ('diagnosing', 'Diagnosing'), ('awaiting_parts', 'Awaiting parts'), ('in_progress', 'In progress'), ('ready', 'Ready for pickup'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('complaint', models.TextField(verbose_name="Customer's complaint / work requested")),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnosis / work notes')),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odometer (km)')),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Mechanic')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='sales.customer')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='sales.sale')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customervehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate per hour')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour', to='workshop.jobcard')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='workshop.jobcard')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.part')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
